pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Test'){
            agent {label 'localizacion_ar_v12'}
            steps {
                sh 'chmod +x scripts/test_localization.sh && scripts/./test_localization.sh CASCARON ' + env.sourceBranch
                sh 'cp /opt/odoo_addons_l10n_ar/junit.xml /var/lib/jenkins/workspace/CASCARON_12_PIPELINE'
                junit '**.xml'
            }
        }
    }
}